# Generated by Django 3.2.4 on 2021-07-24 17:12

from django.db import migrations, models
import oauth2.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('discord_tag', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=100)),
                ('public_flags', models.BigIntegerField()),
                ('flags', models.BigIntegerField()),
                ('locale', models.CharField(max_length=100)),
                ('mfa_enabled', models.BooleanField()),
                ('last_login', models.DateTimeField(null=True)),
            ],
            managers=[
                ('objects', oauth2.managers.DiscordUserOAuth2Manager()),
            ],
        ),
    ]
